spring:

  application:
    name: ${APPLICATION_NAME:street_choosing}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/street_choosing?currentSchema=${spring.application.name}}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}
