INSERT INTO city (name)
VALUES ('Wroclaw');

INSERT INTO street (city_id, name)
VALUES (1, '3 Maja'),
       (1, '9 Maja'),
       (1, 'Abramowskiego Edwarda'),
       (1, 'Adamczewskich Heleny I Ludwika'),
       (1, 'Adamieckiego Karola'),
       (1, 'Afgańska'),
       (1, 'Agatowa'),
       (1, 'Agrestowa'),
       (1, 'Akacjowa Al.'),
       (1, 'Aliancka'),
       (1, 'Alpejska'),
       (1, 'Altanowa'),
       (1, 'Ałunowa'),
       (1, 'Amarantowa'),
       (1, 'Ametystowa'),
       (1, 'Ananasowa'),
       (1, 'Anczyca Władysława'),
       (1, 'Angielska'),
       (1, 'Anonima Galla'),
       (1, 'Aptekarska'),
       (1, 'Arabska'),
       (1, 'Arachidowa'),
       (1, 'Arbuzowa'),
       (1, 'Archeologów'),
       (1, 'Arctowskiego Henryka'),
       (1, 'Armi Krajowej'),
       (1, 'Armii Krajowej Al.'),
       (1, 'Armii Ludowej'),
       (1, 'Arrasowa'),
       (1, 'Artyleryjska'),
       (1, 'Asfaltowa'),
       (1, 'Asnyka Adama'),
       (1, 'Astrowa'),
       (1, 'Augustowska'),
       (1, 'Australijska'),
       (1, 'Azaliowa'),
       (1, 'Babimojska'),
       (1, 'Bacciarellego Marcellego'),
       (1, 'Bacha Jana Sebastiana'),
       (1, 'Baczyńskiego Krzysztofa Kamila'),
       (1, 'Badury Jerzego'),
       (1, 'Bagatela'),
       (1, 'Bajana Jerzego'),
       (1, 'Bąka Stanisława'),
       (1, 'Bałkańska'),
       (1, 'Balladyny'),
       (1, 'Balonowa'),
       (1, 'Bałtycka'),
       (1, 'Bałuckiego Michała'),
       (1, 'Balzaka Honoriusza'),
       (1, 'Banacha Stefana'),
       (1, 'Bandtkiego Jerzego Samuela'),
       (1, 'Baranowicka'),
       (1, 'Barczewska'),
       (1, 'Bardzka'),
       (1, 'Barlickiego Norberta'),
       (1, 'Bartla Kazimierza'),
       (1, 'Bartoszowicka'),
       (1, 'Barwinkowa'),
       (1, 'Barycka'),
       (1, 'Batorego Stefana'),
       (1, 'Baudouina De Courtenay Jana'),
       (1, 'Bażancia'),
       (1, 'Becka Józefa (Pułkownika Józefa Becka)'),
       (1, 'Będkowska'),
       (1, 'Bednarska'),
       (1, 'Będzińska'),
       (1, 'Beethovena Ludwiga Van'),
       (1, 'Belgijska'),
       (1, 'Belgradzka'),
       (1, 'Belwederczyków'),
       (1, 'Bema Józefa (Generała Józefa Bema)'),
       (1, 'Bema Józefa Pl. (Generała Józefa Bema)'),
       (1, 'Benedyktyńska'),
       (1, 'Bengalska'),
       (1, 'Beniowskiego Maurycego'),
       (1, 'Berberysowa'),
       (1, 'Berenta Wacława'),
       (1, 'Berlinga Zygmunta (Generała Zygmunta Berlinga)'),
       (1, 'Bernardyńska'),
       (1, 'Beskidzka'),
       (1, 'Beżowa'),
       (1, 'Bezpieczna'),
       (1, 'Biała'),
       (1, 'Białodrzewna'),
       (1, 'Białogardzka'),
       (1, 'Białoruska'),
       (1, 'Białoskórnicza'),
       (1, 'Białostocka'),
       (1, 'Białoszewskiego Mirona'),
       (1, 'Białowieska'),
       (1, 'Białych Goździków'),
       (1, 'Biegasa Bolesława'),
       (1, 'Biegła'),
       (1, 'Bielarska Wyspa'),
       (1, 'Bielawska'),
       (1, 'Bierdzańska'),
       (1, 'Bieruńska'),
       (1, 'Bierutowska'),
       (1, 'Bierzycka'),
       (1, 'Bieszczadzka'),
       (1, 'Biłgorajska'),
       (1, 'Birmańska'),
       (1, 'Biskupa Nankiera Pl.'),
       (1, 'Biskupa Tomasza Pierwszego'),
       (1, 'Biskupia'),
       (1, 'Biwakowa'),
       (1, 'Blacharska'),
       (1, 'Bławatna'),
       (1, 'Błękitna'),
       (1, 'Bliska'),
       (1, 'Blizanowicka'),
       (1, 'Bliźniacza'),
       (1, 'Błogosławionego Czesława'),
       (1, 'Błotna'),
       (1, 'Bobrza'),
       (1, 'Bobrzańska'),
       (1, 'Bocheńska'),
       (1, 'Bociania'),
       (1, 'Boczna'),
       (1, 'Bogedaina Bernarda (Biskupa Bernarda Bogedaina)'),
       (1, 'Bogucicka'),
       (1, 'Bogusławskiego Wojciecha'),
       (1, 'Boguszewskiej Heleny'),
       (1, 'Boguszowska'),
       (1, 'Bohaterów Getta Pl.'),
       (1, 'Boiskowa'),
       (1, 'Bojanowska'),
       (1, 'Bolesława Chrobrego'),
       (1, 'Bolesława Krzywoustego'),
       (1, 'Bolesławiecka'),
       (1, 'Bolkowska'),
       (1, 'Bołtucia Mikołaja (Generała Mikołaja Bołtucia)'),
       (1, 'Bombardierska'),
       (1, 'Bonczyka Norberta (Księdza Norberta Bonczyka)'),
       (1, 'Bora-Komorowskiego Tadeusza (Generała Tadeusza Bora-Komorowskiego)'),
       (1, 'Borelowskiego Marcina'),
       (1, 'Borna Maxa Pl.'),
       (1, 'Borówczana'),
       (1, 'Borowska'),
       (1, 'Boya-Żeleńskiego Tadeusza Al.'),
       (1, 'Bożego Ciała'),
       (1, 'Boznańskiej Olgi'),
       (1, 'Braci Gierymskich'),
       (1, 'Braci Hofmannów'),
       (1, 'Brahmsa Johannesa'),
       (1, 'Brandta Józefa'),
       (1, 'Braniborska'),
       (1, 'Braniewska'),
       (1, 'Brata Alberta'),
       (1, 'Braterska'),
       (1, 'Bratkowa'),
       (1, 'Bratysławska'),
       (1, 'Brązowa'),
       (1, 'Brochowska'),
       (1, 'Brodnicka'),
       (1, 'Brodzińskiego Kazimierza'),
       (1, 'Brodzka'),
       (1, 'Broniewskiego Władysława'),
       (1, 'Brossa Wiktora'),
       (1, 'Browarna'),
       (1, 'Brücknera Aleksandra Al.'),
       (1, 'Brylantowa'),
       (1, 'Brynicka'),
       (1, 'Brzechwy Jana'),
       (1, 'Brzeska'),
       (1, 'Brzezińska'),
       (1, 'Brzóski Stanisława (Księdza Stanisława Brzóski)'),
       (1, 'Brzoskwiniowa'),
       (1, 'Brzostowska'),
       (1, 'Brzozowa'),
       (1, 'Buczacka'),
       (1, 'Budowlana'),
       (1, 'Budziszyńska'),
       (1, 'Buforowa'),
       (1, 'Bujna'),
       (1, 'Bujwida Odona'),
       (1, 'Bukowa'),
       (1, 'Bukowicka'),
       (1, 'Bukowskiego Marcina'),
       (1, 'Bułgarska'),
       (1, 'Buraczana'),
       (1, 'Bursztynowa'),
       (1, 'Burzowa'),
       (1, 'Buska'),
       (1, 'Byczyńska'),
       (1, 'Bydgoska'),
       (1, 'Bystra'),
       (1, 'Bystrzycka'),
       (1, 'Bytomska'),
       (1, 'Bytowska'),
       (1, 'Bzowa'),
       (1, 'Bzowy Pl.'),
       (1, 'Cabaja Romualda'),
       (1, 'Canaletta Belotta Bernarda'),
       (1, 'Cedrowa'),
       (1, 'Cegielskiego Hipolita'),
       (1, 'Ceglana'),
       (1, 'Celtycka'),
       (1, 'Cementowa'),
       (1, 'Centralna'),
       (1, 'Cerekwicka'),
       (1, 'Cesarzowicka'),
       (1, 'Chabrowa'),
       (1, 'Chałubińskiego Tytusa'),
       (1, 'Chałupnicza'),
       (1, 'Charkowska'),
       (1, 'Chęcińska'),
       (1, 'Chełmońskiego Józefa'),
       (1, 'Chełmska'),
       (1, 'Chemiczna'),
       (1, 'Chińska'),
       (1, 'Chlebowa'),
       (1, 'Chłodna'),
       (1, 'Chłopska'),
       (1, 'Chmielna'),
       (1, 'Chmurna'),
       (1, 'Chobieńska'),
       (1, 'Chociebuska'),
       (1, 'Chocimska'),
       (1, 'Chodkiewicza Jana Karola'),
       (1, 'Chojnowska'),
       (1, 'Cholewkarska'),
       (1, 'Chopina Fryderyka'),
       (1, 'Chorwacka'),
       (1, 'Chorzowska'),
       (1, 'Chrzanowskiego Ignacego'),
       (1, 'Chudoby Stanisława'),
       (1, 'Chwalimierska'),
       (1, 'Chwałkowska'),
       (1, 'Chyżan'),
       (1, 'Cicha'),
       (1, 'Ciechocińska'),
       (1, 'Ciepła'),
       (1, 'Cieplicka'),
       (1, 'Ciesielski Pl.'),
       (1, 'Cieślikowskiego Jerzego'),
       (1, 'Cieszkowskiego Augusta'),
       (1, 'Cieszyńskiego Antoniego'),
       (1, 'Cinciały Andrzeja'),
       (1, 'Cisowa'),
       (1, 'Conrada-Korzeniowskiego Józefa Wybrz.'),
       (1, 'Cukiernicza'),
       (1, 'Cukrowa'),
       (1, 'Curie-Skłodowskiej Marii'),
       (1, 'Ćwiczebna'),
       (1, 'Cybulskiego Wojciecha'),
       (1, 'Cynamonowa'),
       (1, 'Cynowa'),
       (1, 'Cytrynowa'),
       (1, 'Czackiego Tadeusza'),
       (1, 'Czajcza'),
       (1, 'Czajkowskiego Piotra'),
       (1, 'Czaplińskiego Władysława'),
       (1, 'Czarnego Zawiszy'),
       (1, 'Czarnieckiego Stefana'),
       (1, 'Czarnoleska'),
       (1, 'Czechowa Antoniego'),
       (1, 'Czechowicka'),
       (1, 'Czekoladowa'),
       (1, 'Czeremchowa'),
       (1, 'Czereśniowa'),
       (1, 'Czerniawska'),
       (1, 'Czerwonego Krzyża'),
       (1, 'Czerwonych Maków'),
       (1, 'Czeska'),
       (1, 'Częstochowska'),
       (1, 'Czołgistów'),
       (1, 'Czorsztyńska'),
       (1, 'Czysta'),
       (1, 'Czysty Pl.'),
       (1, 'Czytankowa'),
       (1, 'Dąbka Abrahama Stanisława'),
       (1, 'Dąbka Stanisława (Pułkownika Stanisława Dąbka)'),
       (1, 'Dąbrowskiego Jana Henryka (Generała Jana Henryka Dąbrowskiego)'),
       (1, 'Dąbrowskiej Marii'),
       (1, 'Dąbska Al.'),
       (1, 'Daktylowa'),
       (1, 'Daleka'),
       (1, 'Dalemińców'),
       (1, 'Dalimira'),
       (1, 'Daliowa'),
       (1, 'Damrota Konstantego (Księdza Konstantego Damrota)'),
       (1, 'Daniłowskiego Gustawa Pl.'),
       (1, 'Darłowska'),
       (1, 'Darwina Karola'),
       (1, 'Daszyńskiego Ignacego'),
       (1, 'Dawida Jana Władysława'),
       (1, 'Dębicka'),
       (1, 'Dębickiego Zdzisława'),
       (1, 'Dębowa Al.'),
       (1, 'Dedala Bulw.'),
       (1, 'Dekarska'),
       (1, 'Dembowskiego Edwarda'),
       (1, 'Dereniowa'),
       (1, 'Desantowa'),
       (1, 'Deszczowa'),
       (1, 'Diamentowa'),
       (1, 'Dicksteina Samuela'),
       (1, 'Długa'),
       (1, 'Długopolska'),
       (1, 'Długosza Jana'),
       (1, 'Dłutowa'),
       (1, 'Dmowskiego Romana'),
       (1, 'Dobra'),
       (1, 'Dobrackiego Macieja'),
       (1, 'Dobroszycka'),
       (1, 'Dobrzańska'),
       (1, 'Dobrzykowicka'),
       (1, 'Dobrzyńska'),
       (1, 'Dojazd'),
       (1, 'Dokerska'),
       (1, 'Dołęgi-Mostowicza Tadeusza'),
       (1, 'Dolna'),
       (1, 'Dolnobrzeska'),
       (1, 'Domasławska'),
       (1, 'Domeyki Ignacego'),
       (1, 'Dominikański Pl.'),
       (1, 'Dożynkowa'),
       (1, 'Drabika Stanisława'),
       (1, 'Drahonowskiej Olgi'),
       (1, 'Drobnera Bolesława'),
       (1, 'Drobuta Jana'),
       (1, 'Drogosławicka'),
       (1, 'Drohobycka'),
       (1, 'Dróżnicza'),
       (1, 'Druckiego-Lubeckiego Franciszka Ksawerego'),
       (1, 'Drukarska'),
       (1, 'Drzewieckiego Stefana'),
       (1, 'Drzewna'),
       (1, 'Drzymały Michała'),
       (1, 'Dubois Stanisława'),
       (1, 'Dubrownicka'),
       (1, 'Duńska'),
       (1, 'Dusznicka'),
       (1, 'Dworcowa'),
       (1, 'Dworska'),
       (1, 'Dygasińskiego Adolfa'),
       (1, 'Dygata Stanisława'),
       (1, 'Dyrekcyjna'),
       (1, 'Dziadoszańska'),
       (1, 'Działdowska'),
       (1, 'Działkowa'),
       (1, 'Dziarska'),
       (1, 'Dzielna'),
       (1, 'Dzielnicowa'),
       (1, 'Dzierżonia Jana (Księdza Jana Dzierżonia)'),
       (1, 'Dzierżoniowska'),
       (1, 'Dziwnowska'),
       (1, 'Dźwirzyńska'),
       (1, 'Ekonomiczna'),
       (1, 'Ekspresowa'),
       (1, 'Elbląska'),
       (1, 'Ełcka'),
       (1, 'Elementarzowa'),
       (1, 'Elsnera Józefa'),
       (1, 'Eluarda Pawła'),
       (1, 'Energetyczna'),
       (1, 'Estońska'),
       (1, 'Etnografów'),
       (1, 'Fabryczna'),
       (1, 'Fałata Juliana'),
       (1, 'Falskiego Mariana'),
       (1, 'Falzmanna Michała Tadeusza'),
       (1, 'Farna'),
       (1, 'Fasolowa'),
       (1, 'Feichta Hieronima (Księdza Hieronima Feichta)'),
       (1, 'Filipińska'),
       (1, 'Filipowicza Juliana (Generała Juliana Filipowicza)'),
       (1, 'Filomatów'),
       (1, 'Fioletowa'),
       (1, 'Fiołkowa'),
       (1, 'Fizylierska'),
       (1, 'Folwarczna'),
       (1, 'Forsycjowa'),
       (1, 'Forteczna'),
       (1, 'Fortowa'),
       (1, 'Franciszkańska'),
       (1, 'Franciszkański Pl.'),
       (1, 'Francuska'),
       (1, 'Franki Iwana'),
       (1, 'Frankowskiego Stefana (Kontradmirała Stefana Frankowskiego)'),
       (1, 'Fromborska'),
       (1, 'Frycza-Modrzewskiego Andrzeja'),
       (1, 'Fryzjerska'),
       (1, 'Gądowska'),
       (1, 'Gagarina Jurija'),
       (1, 'Gajowa'),
       (1, 'Gajowicka'),
       (1, 'Gajowicka'),
       (1, 'Gałczyńskiego Konstantego Ildefonsa'),
       (1, 'Galla Abrahama'),
       (1, 'Gałowska'),
       (1, 'Garbary'),
       (1, 'Gardy Jerzego'),
       (1, 'Garncarska'),
       (1, 'Garncarskie Przejście'),
       (1, 'Garwolińska'),
       (1, 'Gąsiorowskiego Wacława'),
       (1, 'Gazowa'),
       (1, 'Gdacjusza Adama'),
       (1, 'Gdańska'),
       (1, 'Generała Romana Abrahama'),
       (1, 'Geodezyjna'),
       (1, 'Gepperta Eugeniusza'),
       (1, 'Gerberowa'),
       (1, 'Gersona Wojciecha'),
       (1, 'Gęsia'),
       (1, 'Giełdowa'),
       (1, 'Gielniaka Józefa'),
       (1, 'Gimnazjalna'),
       (1, 'Gitarowa'),
       (1, 'Giżycka'),
       (1, 'Giżyckiego Kamila'),
       (1, 'Glebowa'),
       (1, 'Głębowicka'),
       (1, 'Gliniana'),
       (1, 'Gliwicka'),
       (1, 'Glogera Zygmunta'),
       (1, 'Głogowczyka Jana'),
       (1, 'Głogowska'),
       (1, 'Głośna'),
       (1, 'Głowackiego Bartosza'),
       (1, 'Główna'),
       (1, 'Głubczycka'),
       (1, 'Głuszycka'),
       (1, 'Gminna'),
       (1, 'Gnieźnieńska'),
       (1, 'Godebskiego Cypriana'),
       (1, 'Godlewskiego Aleksandra'),
       (1, 'Goetla Walerego'),
       (1, 'Gogolińska'),
       (1, 'Gołębia'),
       (1, 'Goleszan'),
       (1, 'Gołężycka'),
       (1, 'Gołnowska'),
       (1, 'Gombrowicza Witolda'),
       (1, 'Goplan'),
       (1, 'Góralska'),
       (1, 'Górecka'),
       (1, 'Gorlicka'),
       (1, 'Górnickiego Łukasza'),
       (1, 'Górnicza'),
       (1, 'Górnośląska'),
       (1, 'Górowska'),
       (1, 'Gosławicka'),
       (1, 'Gospodarska'),
       (1, 'Gostyńska'),
       (1, 'Goszczyńskiego Seweryna'),
       (1, 'Grabarska'),
       (1, 'Grabiszyńska'),
       (1, 'Grabowa'),
       (1, 'Grabskiego Władysława'),
       (1, 'Gradowa'),
       (1, 'Granatowa'),
       (1, 'Graniczna'),
       (1, 'Granitowa'),
       (1, 'Grawerska'),
       (1, 'Grecka'),
       (1, 'Grochowa'),
       (1, 'Grochowiaka Stanisława'),
       (1, 'Grodecka'),
       (1, 'Grodzieńska'),
       (1, 'Grodzka'),
       (1, 'Grójecka'),
       (1, 'Gromadzka'),
       (1, 'Grota-Roweckiego Stefana (Generała Stefana Grota-Roweckiego)'),
       (1, 'Grottgera Artura'),
       (1, 'Grudziądzka'),
       (1, 'Grunwaldzka'),
       (1, 'Grunwaldzki Pl.'),
       (1, 'Gruszowa'),
       (1, 'Grybowska'),
       (1, 'Gryczana'),
       (1, 'Grzmota-Skotnickiego Stanisława (Generała Stanisława Grzmota-Skotnickiego)'),
       (1, 'Gubińska'),
       (1, 'Gwarecka'),
       (1, 'Gwarna'),
       (1, 'Gwiaździsta'),
       (1, 'Gwizdanowska'),
       (1, 'Haisiga Mariana'),
       (1, 'Hajducka'),
       (1, 'Hallera Józefa Al. (Generała Józefa Hallera)'),
       (1, 'Hallera Józefa Al. (Generała Józefa Hallera)'),
       (1, 'Halna'),
       (1, 'Halskiej Haliny'),
       (1, 'Handelsmana Marcelego'),
       (1, 'Harcerska'),
       (1, 'Hartmana Stanisława'),
       (1, 'Haukego-Bosaka Józefa (Generała Józefa Haukego-Bosaka)'),
       (1, 'Heblarska'),
       (1, 'Helska'),
       (1, 'Henryka Brodatego'),
       (1, 'Henryka Pobożnego'),
       (1, 'Henrykowska'),
       (1, 'Hercena Aleksandra'),
       (1, 'Hermanowska'),
       (1, 'Hetmańska'),
       (1, 'Heweliusza Jana'),
       (1, 'Himalajska'),
       (1, 'Hippiczna'),
       (1, 'Hirszfelda Ludwika Pl.'),
       (1, 'Hiszpańska'),
       (1, 'Hłaski Marka'),
       (1, 'Hlonda Augusta (Augusta Kardynała Hlonda)'),
       (1, 'Hodowlana'),
       (1, 'Hoene-Wrońskiego Józefa Marii'),
       (1, 'Hokeistów'),
       (1, 'Holenderska'),
       (1, 'Horbaczewskiego Eugeniusza'),
       (1, 'Hoża'),
       (1, 'Hubska'),
       (1, 'Hufcowa'),
       (1, 'Husarska'),
       (1, 'Husycka'),
       (1, 'Hutnicza'),
       (1, 'Hynka Franciszka'),
       (1, 'Ibn Siny Awicenny'),
       (1, 'Icchaka Lejba Pereca Pl.'),
       (1, 'Idzikowskiego Ludwika'),
       (1, 'Igielna'),
       (1, 'Iglasta'),
       (1, 'Ignuta Piotra'),
       (1, 'Ikara Bulw.'),
       (1, 'Iławska'),
       (1, 'Imbirowa'),
       (1, 'Indyjski Pl.'),
       (1, 'Inflancka'),
       (1, 'Inowrocławska'),
       (1, 'Inspektowa'),
       (1, 'Inżynierska'),
       (1, 'Iracka'),
       (1, 'Irkucka'),
       (1, 'Irlandzka'),
       (1, 'Irysowa'),
       (1, 'Iwaszkiewicza Jarosława'),
       (1, 'Iwonicka'),
       (1, 'Jabłeczna'),
       (1, 'Jackowskiego Maksymiliana'),
       (1, 'Jagiellończyka Kazimierza'),
       (1, 'Jagiellońska'),
       (1, 'Jaglana'),
       (1, 'Jagniątkowska'),
       (1, 'Jagodowa'),
       (1, 'Jagodzińska'),
       (1, 'Jahna Alfreda'),
       (1, 'Jajczarska'),
       (1, 'Jaksonowicka'),
       (1, 'Jana Pawła Ii Pl.'),
       (1, 'Janickiego Klemensa'),
       (1, 'Janiszewskiego Zygmunta'),
       (1, 'Janowska'),
       (1, 'Jantarowa'),
       (1, 'Januszowicka'),
       (1, 'Japońska'),
       (1, 'Jaracza Stefana'),
       (1, 'Jareckiego Henryka'),
       (1, 'Jarnołtowska'),
       (1, 'Jarocińska'),
       (1, 'Jarosławska'),
       (1, 'Jarzębinowa Al.'),
       (1, 'Jarzynowa'),
       (1, 'Jasielska'),
       (1, 'Jasienicy Pawła'),
       (1, 'Jasińskiego Tadka Bulw.'),
       (1, 'Jasińskiej Anny'),
       (1, 'Jaskółcza'),
       (1, 'Jaśkowicka'),
       (1, 'Jaśminowa'),
       (1, 'Jasna'),
       (1, 'Jaspisowa'),
       (1, 'Jastrzębia'),
       (1, 'Jatki'),
       (1, 'Jaworowa Al.'),
       (1, 'Jaworska'),
       (1, 'Jaworskiego Iwo'),
       (1, 'Jaźwińska'),
       (1, 'Jęczmienna'),
       (1, 'Jedności Narodowej'),
       (1, 'Jędrzejowska'),
       (1, 'Jelczańska'),
       (1, 'Jelenia'),
       (1, 'Jeleniogórska'),
       (1, 'Jemeńska'),
       (1, 'Jemiołowa'),
       (1, 'Jerzmanowska'),
       (1, 'Jesienna'),
       (1, 'Jesiennicka'),
       (1, 'Jesionowa'),
       (1, 'Jeździecka'),
       (1, 'Jezierskiego Franciszka Salezego (Księdza Franciszka Salezego Jezierskiego)'),
       (1, 'Jeziorowa'),
       (1, 'Jeżowska'),
       (1, 'Joannitów'),
       (1, 'Jodłowa'),
       (1, 'Joliot-Curie Fryderyka'),
       (1, 'Jordanowska'),
       (1, 'Jordańska'),
       (1, 'Jubilerska'),
       (1, 'Jugosłowiańska'),
       (1, 'Junacka'),
       (1, 'Juszczaka Franciszka'),
       (1, 'Jutrosińska'),
       (1, 'Jutrzenki'),
       (1, 'Kącka'),
       (1, 'Kaczeńcowa'),
       (1, 'Kaczmarskiego Jacka'),
       (1, 'Kadłubka Wincentego (Błogosławionego Wincentego Kadłubka)'),
       (1, 'Kajakarzy'),
       (1, 'Kaletnicza'),
       (1, 'Kalinowa'),
       (1, 'Kaliski Pl.'),
       (1, 'Kamieniecka'),
       (1, 'Kamienna'),
       (1, 'Kamiennogórska'),
       (1, 'Kamieńskiego Henryka Michała'),
       (1, 'Kampinoska'),
       (1, 'Kanadyjska'),
       (1, 'Kanałowa'),
       (1, 'Kanonia'),
       (1, 'Kanonierska Al.'),
       (1, 'Kapistrana Jana (Świętego Jana Kapistrana)'),
       (1, 'Kapitulna'),
       (1, 'Kapliczna'),
       (1, 'Karczemna'),
       (1, 'Karkonoska Al.'),
       (1, 'Karłowicza Mieczysława'),
       (1, 'Karmelkowa'),
       (1, 'Karmelkowa'),
       (1, 'Karpacka'),
       (1, 'Karpińskiego Franciszka'),
       (1, 'Karwińska'),
       (1, 'Kasprowicza Jana Al.'),
       (1, 'Kasprzaka Marcina'),
       (1, 'Kasztanowa Al.'),
       (1, 'Kasztelańska'),
       (1, 'Kaszubska'),
       (1, 'Katedralna'),
       (1, 'Katedralny Pl.'),
       (1, 'Kątowa'),
       (1, 'Katowicka'),
       (1, 'Kawalerzystów'),
       (1, 'Kazimierska'),
       (1, 'Kaznodziejska'),
       (1, 'Kępa Mieszczańska Wyspa'),
       (1, 'Kępińska'),
       (1, 'Ketlinga'),
       (1, 'Kiełbaśnicza'),
       (1, 'Kiełczowska'),
       (1, 'Kielecka'),
       (1, 'Kiemliczów'),
       (1, 'Kiepury Jana'),
       (1, 'Kilińskiego Jana'),
       (1, 'Klaczki Juliana'),
       (1, 'Klasztorna'),
       (1, 'Klecińska'),
       (1, 'Kleczkowska'),
       (1, 'Kleeberga Franciszka (Generała Franciszka Kleeberga)'),
       (1, 'Klimasa Czesława (Księdza Czesława Klimasa)'),
       (1, 'Kłodnicka'),
       (1, 'Kłodzka'),
       (1, 'Kłokoczycka'),
       (1, 'Klonowa Al.'),
       (1, 'Kłośna'),
       (1, 'Kluczborska'),
       (1, 'Kmicica Andrzeja'),
       (1, 'Kmieca'),
       (1, 'Kminkowa'),
       (1, 'Knastera Bronisława'),
       (1, 'Kniaziewicza Karola (Generała Karola Kniaziewicza)'),
       (1, 'Knignicka'),
       (1, 'Knota Antoniego'),
       (1, 'Kobierzycka'),
       (1, 'Kocha Roberta'),
       (1, 'Kochanowskiego Jana Al.'),
       (1, 'Kochłowicka'),
       (1, 'Kokosowa'),
       (1, 'Kolarska'),
       (1, 'Kolberga Oskara'),
       (1, 'Kolbuszowska'),
       (1, 'Kolejowa'),
       (1, 'Kolendrowa'),
       (1, 'Kolista'),
       (1, 'Kołłątaja Hugona'),
       (1, 'Kołobrzeska'),
       (1, 'Kołodziejska'),
       (1, 'Kolumba Krzysztofa'),
       (1, 'Komandorska'),
       (1, 'Komandorska'),
       (1, 'Komeńskiego Jana Amosa'),
       (1, 'Kominiarska'),
       (1, 'Kominka Bolesława (Bolesława Kardynała Kominka)'),
       (1, 'Komorowska'),
       (1, 'Komuny Paryskiej'),
       (1, 'Konarskiego Szymona'),
       (1, 'Końcowa'),
       (1, 'Konduktorska'),
       (1, 'Koniecpolskiego Stanisława'),
       (1, 'Konińska'),
       (1, 'Konopnickiej Marii'),
       (1, 'Końska'),
       (1, 'Konstytucji 3 Maja Pl.'),
       (1, 'Konwaliowa'),
       (1, 'Kopańskiego Stanisława (Generała Stanisława Kopańskiego)'),
       (1, 'Kopernika Mikołaja'),
       (1, 'Korczaka Janusza'),
       (1, 'Kordeckiego Augustyna (Księdza Augustyna Kordeckiego)'),
       (1, 'Kordiana'),
       (1, 'Koreańska'),
       (1, 'Korfantego Wojciecha'),
       (1, 'Korzeńska'),
       (1, 'Kościańska'),
       (1, 'Kościelna'),
       (1, 'Kościelny Pl.'),
       (1, 'Kościerzyńska'),
       (1, 'Kościuszki Tadeusza'),
       (1, 'Kościuszki Tadeusza'),
       (1, 'Kościuszki Tadeusza Pl.'),
       (1, 'Kosiby Aleksandra'),
       (1, 'Kosidowskiego Zenona'),
       (1, 'Kosmiczna'),
       (1, 'Kosmonautów'),
       (1, 'Kośnego Augustyna'),
       (1, 'Kossaka Juliusza'),
       (1, 'Kossak-Szczuckiej Zofii'),
       (1, 'Kostrzyńska'),
       (1, 'Kosynierów Gdyńskich'),
       (1, 'Koszalińska'),
       (1, 'Koszarowa'),
       (1, 'Koszycka'),
       (1, 'Koszykarska'),
       (1, 'Koszykarzy'),
       (1, 'Kotlarska'),
       (1, 'Kotsisa Aleksandra'),
       (1, 'Kowalska'),
       (1, 'Kowalskiego Jerzego'),
       (1, 'Kowieńska'),
       (1, 'Kozanowska'),
       (1, 'Kozanowska Grobla'),
       (1, 'Kozia'),
       (1, 'Kozielska'),
       (1, 'Kożuchowska'),
       (1, 'Kraińskiego Wincentego (Księdza Wincentego Kraińskiego)'),
       (1, 'Krajewskiego Rafała'),
       (1, 'Krajobrazowa'),
       (1, 'Krakowska'),
       (1, 'Krakusa'),
       (1, 'Krasickiego Ignacego (Biskupa Ignacego Krasickiego)'),
       (1, 'Krasińskiego Zygmunta'),
       (1, 'Kraszewskiego Józefa Ignacego'),
       (1, 'Krawiecka'),
       (1, 'Krępicka'),
       (1, 'Kreślarska'),
       (1, 'Kresowa'),
       (1, 'Kręta'),
       (1, 'Krokusowa'),
       (1, 'Królewiecka'),
       (1, 'Królewska'),
       (1, 'Królowej Marysieńki'),
       (1, 'Kromera Marcina Al.'),
       (1, 'Krośnicka'),
       (1, 'Krośnieńska'),
       (1, 'Krótka'),
       (1, 'Krotoszyńska'),
       (1, 'Krowia'),
       (1, 'Krucza'),
       (1, 'Kruczkowskiego Leona'),
       (1, 'Krupnicza'),
       (1, 'Kruszcowa'),
       (1, 'Kruszwicka'),
       (1, 'Krynicka'),
       (1, 'Kryniczna'),
       (1, 'Kryształowa'),
       (1, 'Krzelowska'),
       (1, 'Krzemieniecka'),
       (1, 'Krzeptowska'),
       (1, 'Krzeszowska'),
       (1, 'Krzycka'),
       (1, 'Krzywa'),
       (1, 'Krzywa Grobla'),
       (1, 'Krzywickiego Ludwika'),
       (1, 'Krzyżanowicka'),
       (1, 'Krzyżowska'),
       (1, 'Księcia Witolda'),
       (1, 'Księgarska'),
       (1, 'Księgowa'),
       (1, 'Księska'),
       (1, 'Księżycowa'),
       (1, 'Kubali Ludwika'),
       (1, 'Kudowska'),
       (1, 'Kujbyszewska'),
       (1, 'Kukuczki Jerzego'),
       (1, 'Kukułcza'),
       (1, 'Kunickiego Stanisława'),
       (1, 'Kupiecka'),
       (1, 'Kurkowa'),
       (1, 'Kuronia Jacka'),
       (1, 'Kuropatwia'),
       (1, 'Kurpiów'),
       (1, 'Kurska'),
       (1, 'Kurzy Targ'),
       (1, 'Kusztelana Stanisława'),
       (1, 'Kutnowska'),
       (1, 'Kutrzeby Tadeusza (Generała Tadeusza Kutrzeby)'),
       (1, 'Kuźnicza'),
       (1, 'Kwaśna'),
       (1, 'Kwiatkowskiego Eugeniusza'),
       (1, 'Kwiatkowskiego Eugeniusza'),
       (1, 'Kwiatowa'),
       (1, 'Kwidzyńska'),
       (1, 'Kwiska'),
       (1, 'Kwitnąca'),
       (1, 'Łaciarska'),
       (1, 'Łączna'),
       (1, 'Łączności'),
       (1, 'Lądecka'),
       (1, 'Ładna'),
       (1, 'Łagiewnicka'),
       (1, 'Łąka Mazurska'),
       (1, 'Lakiernicza'),
       (1, 'Łąkowa'),
       (1, 'Łaniewska'),
       (1, 'Łaniewska Grobla'),
       (1, 'Łanowa'),
       (1, 'Łanowskiego Jerzego'),
       (1, 'Laotańska'),
       (1, 'Łaska'),
       (1, 'Laskowicka'),
       (1, 'Lassalla Ferdynanda Zaułek'),
       (1, 'Latawcowa'),
       (1, 'Lawendowa'),
       (1, 'Łazienna'),
       (1, 'Lazurowa'),
       (1, 'Lechitów'),
       (1, 'Lechonia Jana'),
       (1, 'Łęczycka'),
       (1, 'Ledóchowskiego Mieczysława (Mieczysława Kardynała Ledóchowskiego)'),
       (1, 'Legionów Pl.'),
       (1, 'Legnicka'),
       (1, 'Legnicka'),
       (1, 'Lekarska'),
       (1, 'Lekcyjna'),
       (1, 'Lelewela Joachima'),
       (1, 'Lenartowicza Teofila'),
       (1, 'Leśmiana Bolesława'),
       (1, 'Leśna'),
       (1, 'Leszczynowa'),
       (1, 'Leszczyńskiego Stanisława'),
       (1, 'Letnia'),
       (1, 'Lewa'),
       (1, 'Libelta Karola'),
       (1, 'Lidzbarska'),
       (1, 'Ligocka'),
       (1, 'Liliowa'),
       (1, 'Limanowska'),
       (1, 'Lindego Samuela Bogumiła'),
       (1, 'Linkego Godfryda'),
       (1, 'Lipińskiego Karola'),
       (1, 'Lipowa Al.'),
       (1, 'Lipska'),
       (1, 'Liściasta'),
       (1, 'Lisia'),
       (1, 'Lisicka'),
       (1, 'Liskego Ksawerego'),
       (1, 'Litewska'),
       (1, 'Litomska'),
       (1, 'Lniana'),
       (1, 'Łódzka'),
       (1, 'Łomnicka'),
       (1, 'Lompy Józefa'),
       (1, 'Łopianowa'),
       (1, 'Łososiowicka'),
       (1, 'Lotnicza'),
       (1, 'Łowiecka'),
       (1, 'Lubczykowa'),
       (1, 'Lubelska'),
       (1, 'Lubiąska'),
       (1, 'Łubinowa'),
       (1, 'Lubińska'),
       (1, 'Lublańska'),
       (1, 'Lubska'),
       (1, 'Lubuska'),
       (1, 'Łuczan'),
       (1, 'Łuczników'),
       (1, 'Ludowa'),
       (1, 'Ługowa'),
       (1, 'Ługowińska'),
       (1, 'Łukasiewicza Ignacego'),
       (1, 'Łukasińskiego Waleriana'),
       (1, 'Łukowa'),
       (1, 'Łukowska'),
       (1, 'Lutycka'),
       (1, 'Lutyńska'),
       (1, 'Łużycka'),
       (1, 'Lwowska'),
       (1, 'Łysogórska'),
       (1, 'Łyżwiarzy'),
       (1, 'Macedońska'),
       (1, 'Machnicka'),
       (1, 'Maczka Stanisława (Generała Stanisława Maczka)'),
       (1, 'Mączna'),
       (1, 'Magellana Ferdynanda'),
       (1, 'Majakowskiego Włodzimierza'),
       (1, 'Majchra Alojzego'),
       (1, 'Majora Hubala'),
       (1, 'Makowa'),
       (1, 'Makuszyńskiego Kornela'),
       (1, 'Malachitowa'),
       (1, 'Małachowskiego Stanisława'),
       (1, 'Malarska'),
       (1, 'Malborska'),
       (1, 'Malczewskiego Jacka'),
       (1, 'Malczycka'),
       (1, 'Maleczyńskich Ewy I Karola'),
       (1, 'Malinowa'),
       (1, 'Małkowskiego Andrzeja'),
       (1, 'Małomicka'),
       (1, 'Małopanewska'),
       (1, 'Małopolska'),
       (1, 'Małoszyńska'),
       (1, 'Malownicza'),
       (1, 'Malwowa'),
       (1, 'Mandarynkowa'),
       (1, 'Mandżurska'),
       (1, 'Manganowa'),
       (1, 'Marcepanowa'),
       (1, 'Marchewkowa'),
       (1, 'Marcinkowskiego Karola'),
       (1, 'Marczewskiego Edwarda'),
       (1, 'Markowskiego Zygmunta'),
       (1, 'Marmurowa'),
       (1, 'Marsowa'),
       (1, 'Marszowicka'),
       (1, 'Marynarska'),
       (1, 'Maślicka'),
       (1, 'Masztalerza Kazimierza (Pułkownika Kazimierza Masztalerza)'),
       (1, 'Masztowa'),
       (1, 'Matejki Jana Al.'),
       (1, 'Mazepy'),
       (1, 'Mazowiecka'),
       (1, 'Mechaników'),
       (1, 'Męcińskiego Wojciecha'),
       (1, 'Meissnera Janusza'),
       (1, 'Meliorancka'),
       (1, 'Mennicza'),
       (1, 'Metalowców'),
       (1, 'Mewia'),
       (1, 'Mianowskiego Józefa'),
       (1, 'Miarki Karola'),
       (1, 'Michalczyka Kazimierza'),
       (1, 'Michałowskiego Piotra'),
       (1, 'Micińskiego Tadeusza'),
       (1, 'Mickiewicza Adama'),
       (1, 'Miechowity Macieja'),
       (1, 'Miechowska'),
       (1, 'Mieczykowa'),
       (1, 'Miedziana'),
       (1, 'Międzygórska'),
       (1, 'Międzyleska'),
       (1, 'Międzyrzecka'),
       (1, 'Międzyzdrojska'),
       (1, 'Miejska'),
       (1, 'Mielczarskiego Romualda'),
       (1, 'Mielecka'),
       (1, 'Miernicza'),
       (1, 'Mierosławskiego Ludwika (Generała Ludwika Mierosławskiego)'),
       (1, 'Mieroszowska'),
       (1, 'Mieszczańska'),
       (1, 'Mieszka I'),
       (1, 'Miętowa'),
       (1, 'Migdałowa'),
       (1, 'Mikołowska'),
       (1, 'Mikory'),
       (1, 'Mikulicza-Radeckiego Jana'),
       (1, 'Mikulskiego Tadeusza'),
       (1, 'Miła'),
       (1, 'Milenijna'),
       (1, 'Milicka'),
       (1, 'Miłkowska'),
       (1, 'Miłostowska'),
       (1, 'Miłoszycka'),
       (1, 'Minkowskiego Oskara'),
       (1, 'Mińska'),
       (1, 'Miodowa'),
       (1, 'Mirtowa'),
       (1, 'Mleczarska'),
       (1, 'Młoda'),
       (1, 'Młodnickiego Artura'),
       (1, 'Młodych Techników'),
       (1, 'Młodzieżowa'),
       (1, 'Młynarska'),
       (1, 'Mochnackiego Maurycego'),
       (1, 'Modelskiego Teofila'),
       (1, 'Modlińska'),
       (1, 'Modra'),
       (1, 'Modrzejewskiej Heleny'),
       (1, 'Modrzewiowa'),
       (1, 'Mojęcicka'),
       (1, 'Mokra'),
       (1, 'Mokronoska'),
       (1, 'Mokrzańska'),
       (1, 'Mongolski Pl.'),
       (1, 'Moniuszki Stanisława'),
       (1, 'Monopolowa'),
       (1, 'Monte Cassino'),
       (1, 'Monterska'),
       (1, 'Morawska'),
       (1, 'Morelowskiego Mariana'),
       (1, 'Morska'),
       (1, 'Mosbacha Augusta'),
       (1, 'Mościckiego Ignacego'),
       (1, 'Mosiężna'),
       (1, 'Motylkowa'),
       (1, 'Mrągowska'),
       (1, 'Mroźna'),
       (1, 'Mrozowska'),
       (1, 'Muchoborska'),
       (1, 'Mulicka'),
       (1, 'Murarska'),
       (1, 'Muzealny Pl.'),
       (1, 'Mydlana'),
       (1, 'Mydlarskiego Jana'),
       (1, 'Mysłakowicka'),
       (1, 'Myśliwska'),
       (1, 'Mysłowicka'),
       (1, 'Myszkowska'),
       (1, 'Na Grobli'),
       (1, 'Na Końcu'),
       (1, 'Na Niskich Łąkach'),
       (1, 'Na Ostatnim Groszu'),
       (1, 'Na Polance'),
       (1, 'Na Szańcach'),
       (1, 'Nabielaka Ludwika'),
       (1, 'Nabycińska'),
       (1, 'Nadbrzeżna'),
       (1, 'Nadolicka'),
       (1, 'Nadrzeczna'),
       (1, 'Najświętszej Marii Panny'),
       (1, 'Nałkowskiej Zofii'),
       (1, 'Namysłowska'),
       (1, 'Nankiera Biskupa Pl.'),
       (1, 'Narciarska'),
       (1, 'Narcyzowa'),
       (1, 'Nasienna'),
       (1, 'Nastawnicza'),
       (1, 'Nasturcjowa'),
       (1, 'Nasypowa'),
       (1, 'Nauczycielska'),
       (1, 'Nefrytowa'),
       (1, 'Nehringa Władysława'),
       (1, 'Nektarowa'),
       (1, 'Nenckiego Marcelego'),
       (1, 'Nenufarowa'),
       (1, 'Nepalska'),
       (1, 'Niborska'),
       (1, 'Niebieska'),
       (1, 'Niecała'),
       (1, 'Niedziałkowskiego Mieczysława'),
       (1, 'Niedźwiedzia'),
       (1, 'Niemcewicza Juliana Ursyna'),
       (1, 'Niemczańska'),
       (1, 'Niemkińska'),
       (1, 'Niepierzyńska'),
       (1, 'Niepodległości'),
       (1, 'Nikliborca Jana'),
       (1, 'Niklowa'),
       (1, 'Nizinna'),
       (1, 'Noakowskiego Stanisława'),
       (1, 'Nobla Alfreda'),
       (1, 'Norblina Piotra'),
       (1, 'Norweska'),
       (1, 'Norwida Cypriana Kamila'),
       (1, 'Noskowskiego Zygmunta'),
       (1, 'Notecka'),
       (1, 'Nowa'),
       (1, 'Nowodworska'),
       (1, 'Nowogródzka'),
       (1, 'Nowohucka'),
       (1, 'Nowosądecka'),
       (1, 'Nowotarska'),
       (1, 'Nowowiejska'),
       (1, 'Nowy Świat'),
       (1, 'Nowy Targ Pl.'),
       (1, 'Nożownicza'),
       (1, 'Nulla Franciszka (Pułkownika Franciszka Nulla)'),
       (1, 'Nyska'),
       (1, 'Objazdowa'),
       (1, 'Obodrzycka'),
       (1, 'Obornicka'),
       (1, 'Oboźna'),
       (1, 'Obrońców Helu Skw.'),
       (1, 'Obrońców Poczty Gdańskiej'),
       (1, 'Odcinek'),
       (1, 'Odeska'),
       (1, 'Odkrywców'),
       (1, 'Odolanowska'),
       (1, 'Odrodzenia Polski'),
       (1, 'Odrzańska'),
       (1, 'Ofiar Oświęcimskich'),
       (1, 'Oficerska'),
       (1, 'Ogórkowa'),
       (1, 'Ogrodowa'),
       (1, 'Ojca Beyzyma'),
       (1, 'Ojców Oblatów'),
       (1, 'Okólna'),
       (1, 'Okrętowa'),
       (1, 'Okrężna'),
       (1, 'Okrzei Stefana'),
       (1, 'Oksywska'),
       (1, 'Okulickiego Leopolda (Generała Leopolda Okulickiego)'),
       (1, 'Oławska'),
       (1, 'Ołbińska'),
       (1, 'Olbrachtowska'),
       (1, 'Oleska'),
       (1, 'Oleśnicka'),
       (1, 'Oliwkowa'),
       (1, 'Olkuska'),
       (1, 'Ołowiana'),
       (1, 'Olszewskiego Karola'),
       (1, 'Olsztyńska'),
       (1, 'Ołtaszyńska'),
       (1, 'Omska'),
       (1, 'Opalowa'),
       (1, 'Opatowicka'),
       (1, 'Opatowicka Grobla'),
       (1, 'Opłotkowa'),
       (1, 'Opoczyńska'),
       (1, 'Opolska'),
       (1, 'Oporowska'),
       (1, 'Oppmana Artura'),
       (1, 'Oraczy'),
       (1, 'Orawska'),
       (1, 'Orkana Władysława'),
       (1, 'Orla'),
       (1, 'Orląt Lwowskich Pl.'),
       (1, 'Orlińskiego Bolesława (Pułkownika Bolesława Orlińskiego)'),
       (1, 'Orłowicza Mieczysława'),
       (1, 'Orłowskiego Aleksandra'),
       (1, 'Orna'),
       (1, 'Orzechowa'),
       (1, 'Orzeszkowej Elizy'),
       (1, 'Osadnicza'),
       (1, 'Osiecka'),
       (1, 'Osiedlowa'),
       (1, 'Osiniecka'),
       (1, 'Osmańczyka Edmunda'),
       (1, 'Osobowicka'),
       (1, 'Osolska'),
       (1, 'Ostowa'),
       (1, 'Ostrężynowa'),
       (1, 'Ostródzka'),
       (1, 'Ostroroga Jana'),
       (1, 'Ostrowska'),
       (1, 'Ostrowskiego Aleksandra'),
       (1, 'Ostrzeszowska'),
       (1, 'Otmuchowska'),
       (1, 'Otwarta'),
       (1, 'Otwocka'),
       (1, 'Otyńska'),
       (1, 'Owczarska'),
       (1, 'Owocowa'),
       (1, 'Owsiana'),
       (1, 'Ożynowa'),
       (1, 'Pabianicka'),
       (1, 'Pachnąca'),
       (1, 'Paczkowska'),
       (1, 'Paderewskiego Jana Ignacego Al.'),
       (1, 'Pakistańska'),
       (1, 'Pakosławska'),
       (1, 'Palacha Jana'),
       (1, 'Palestyńska'),
       (1, 'Palisadowa'),
       (1, 'Pałucka'),
       (1, 'Pamirska'),
       (1, 'Paniowicka'),
       (1, 'Pankiewicza Józefa'),
       (1, 'Papiernicza'),
       (1, 'Paprotna'),
       (1, 'Parafialna'),
       (1, 'Parandowskiego Jana'),
       (1, 'Parkowa'),
       (1, 'Parnickiego Teodora'),
       (1, 'Parowozowa'),
       (1, 'Partynicka'),
       (1, 'Partyzantów'),
       (1, 'Paryska'),
       (1, 'Pasieczna'),
       (1, 'Pasłęcka'),
       (1, 'Pastelowa'),
       (1, 'Pasterska'),
       (1, 'Pasterska'),
       (1, 'Pasteura Ludwika Wybrz.'),
       (1, 'Paulińska'),
       (1, 'Pautscha Fryderyka'),
       (1, 'Pawia'),
       (1, 'Pawłowa Iwana'),
       (1, 'Pawłowicka'),
       (1, 'Pedagogiczna'),
       (1, 'Pęgowska'),
       (1, 'Pękalskiego Stanisława'),
       (1, 'Pełczyńska'),
       (1, 'Pereca Icchaka Lejba'),
       (1, 'Perkusyjna'),
       (1, 'Perłowa'),
       (1, 'Peronowa'),
       (1, 'Perska'),
       (1, 'Perzowa'),
       (1, 'Perzyńskiego Włodzimierza'),
       (1, 'Pestalozziego Jana Henryka'),
       (1, 'Petrażyckiego Leona'),
       (1, 'Petrusewicza Marka'),
       (1, 'Petuniowa'),
       (1, 'Piasek Wyspa'),
       (1, 'Piaskowa'),
       (1, 'Piastów Al.'),
       (1, 'Piastowska'),
       (1, 'Pięćdziesięciu Bohaterów'),
       (1, 'Piechoty'),
       (1, 'Piechowicka'),
       (1, 'Piekarska'),
       (1, 'Piękna'),
       (1, 'Pielęgniarska'),
       (1, 'Pienińska'),
       (1, 'Pieprzna'),
       (1, 'Piernikowa'),
       (1, 'Pierwiosnkowa'),
       (1, 'Pierwszej Dywizji'),
       (1, 'Piesza'),
       (1, 'Pieszycka'),
       (1, 'Piętaka Stanisława'),
       (1, 'Pietrzykowicka'),
       (1, 'Pilata Stanisława'),
       (1, 'Piławska'),
       (1, 'Pilczycka'),
       (1, 'Piłkarzy'),
       (1, 'Pilnikarska'),
       (1, 'Piłsudskiego Józefa (Marszałka Józefa Piłsudskiego)'),
       (1, 'Piłsudskiego Józefa Pl. (Marszałka Józefa Piłsudskiego)'),
       (1, 'Pińska'),
       (1, 'Piołunowa'),
       (1, 'Pionierów'),
       (1, 'Pionierów Wrocławskich Skw.'),
       (1, 'Pionierska'),
       (1, 'Piotrkowska'),
       (1, 'Piramowicza Grzegorza (Księdza Grzegorza Piramowicza)'),
       (1, 'Pirenejska'),
       (1, 'Piwna'),
       (1, 'Piwniczna'),
       (1, 'Piwnika-Ponurego Jana (Majora Jana Piwnika- Ponurego)'),
       (1, 'Piwowarska'),
       (1, 'Płaska'),
       (1, 'Platanowa Al.'),
       (1, 'Plater Emilii'),
       (1, 'Platówny Franciszki'),
       (1, 'Pleszewska'),
       (1, 'Płońskiego Michała'),
       (1, 'Płużna'),
       (1, 'Pochyła'),
       (1, 'Pocztowa'),
       (1, 'Podbiałowa'),
       (1, 'Podchorążych'),
       (1, 'Podolska'),
       (1, 'Podróżnicza'),
       (1, 'Podwale'),
       (1, 'Podwale'),
       (1, 'Podwórcowa'),
       (1, 'Pogodna'),
       (1, 'Pola Wincentego'),
       (1, 'Połabian'),
       (1, 'Polaka Benedykta'),
       (1, 'Połaniecka'),
       (1, 'Polanowicka'),
       (1, 'Polarna'),
       (1, 'Połbina Iwana (Generała Iwana Połbina)'),
       (1, 'Poleska'),
       (1, 'Polkowicka'),
       (1, 'Polna'),
       (1, 'Północna'),
       (1, 'Polo Marca'),
       (1, 'Polonii Wrocławskiej'),
       (1, 'Polski Pl.'),
       (1, 'Południowa'),
       (1, 'Pomarańczowa'),
       (1, 'Pomorska'),
       (1, 'Poniatowskiego Józefa (Józefa Księcia Poniatowskiego)'),
       (1, 'Popielskiego Leona'),
       (1, 'Popowicka'),
       (1, 'Poprzeczna Al.'),
       (1, 'Poranna'),
       (1, 'Porębska'),
       (1, 'Poronińska'),
       (1, 'Portowa'),
       (1, 'Porzeczkowa'),
       (1, 'Postępowa'),
       (1, 'Postolińska'),
       (1, 'Poświęcka'),
       (1, 'Potebni Andrzeja'),
       (1, 'Potockiego Wacława'),
       (1, 'Potokowa'),
       (1, 'Powiewna'),
       (1, 'Powstańców Śląskich'),
       (1, 'Powstańców Śląskich Pl.'),
       (1, 'Powstańców Warszawskich Skw.'),
       (1, 'Powstańców Warszawy Pl.'),
       (1, 'Powstańców Wielkopolskich Pl.'),
       (1, 'Poziomkowa'),
       (1, 'Poznańska'),
       (1, 'Pracka'),
       (1, 'Pracy Al.'),
       (1, 'Prądzyńskiego Ignacego (Generała Ignacego Prądzyńskiego)'),
       (1, 'Prędka'),
       (1, 'Pretficza Bernarda'),
       (1, 'Probusa Henryka'),
       (1, 'Prochowicka'),
       (1, 'Promenada'),
       (1, 'Promień'),
       (1, 'Prosta'),
       (1, 'Prudnicka'),
       (1, 'Prusa Bolesława'),
       (1, 'Prusicka'),
       (1, 'Przebiśniegowa'),
       (1, 'Przechodnia'),
       (1, 'Przedmiejska'),
       (1, 'Przednia'),
       (1, 'Przedświt'),
       (1, 'Przedwiośnie'),
       (1, 'Przejazdowa'),
       (1, 'Przelot'),
       (1, 'Przemiłowska'),
       (1, 'Przemkowska'),
       (1, 'Przemyska'),
       (1, 'Przemysłowa'),
       (1, 'Przerwy-Tetmajera Kazimierza'),
       (1, 'Przesiecka'),
       (1, 'Przeskok'),
       (1, 'Przesmyckiego Zenona Miriama'),
       (1, 'Przestrzenna'),
       (1, 'Przy Torze'),
       (1, 'Przybyły Macieja'),
       (1, 'Przybyszewskiego Stanisława'),
       (1, 'Przyjaźni'),
       (1, 'Przylaszczkowa'),
       (1, 'Przystankowa'),
       (1, 'Psie Budy'),
       (1, 'Pszczelarska'),
       (1, 'Pszczyńska'),
       (1, 'Pszenna'),
       (1, 'Ptasia'),
       (1, 'Pucka'),
       (1, 'Pugeta Ludwika'),
       (1, 'Pułaskiego Kazimierza (Generała Kazimierza Pułaskiego)'),
       (1, 'Pułtuska'),
       (1, 'Purkyniego Jana Ewangelisty'),
       (1, 'Purpurowa'),
       (1, 'Pusta'),
       (1, 'Pustecka'),
       (1, 'Puszczykowska'),
       (1, 'Pyrzycka'),
       (1, 'Rabczańska'),
       (1, 'Racławicka'),
       (1, 'Racławicka'),
       (1, 'Rącza'),
       (1, 'Radarowa'),
       (1, 'Radkowska'),
       (1, 'Radłowa'),
       (1, 'Radomska'),
       (1, 'Radosna'),
       (1, 'Radzionkowska'),
       (1, 'Rajska'),
       (1, 'Rakietowa'),
       (1, 'Rakowa'),
       (1, 'Rakowiecka'),
       (1, 'Rapackiego Mariana'),
       (1, 'Raszowska'),
       (1, 'Rataja Macieja'),
       (1, 'Ratajów'),
       (1, 'Ratyńska'),
       (1, 'Rawicka'),
       (1, 'Rawska'),
       (1, 'Raźna'),
       (1, 'Rdestowa'),
       (1, 'Reagana Ronalda Rondo'),
       (1, 'Redarów'),
       (1, 'Redycka'),
       (1, 'Rędzińska'),
       (1, 'Reja Mikołaja'),
       (1, 'Rejonowa'),
       (1, 'Rejtana Tadeusza'),
       (1, 'Rękodzielnicza'),
       (1, 'Reszelska'),
       (1, 'Rewalska'),
       (1, 'Reymonta Władysława'),
       (1, 'Rezedowa'),
       (1, 'Robotnicza'),
       (1, 'Rodakowskiego Henryka Hipolita'),
       (1, 'Rodziewiczówny Marii'),
       (1, 'Rodzinna'),
       (1, 'Rodzynkowa'),
       (1, 'Roentgena Wilhelma'),
       (1, 'Rogowska'),
       (1, 'Rolna'),
       (1, 'Rolnicza'),
       (1, 'Romanowskiego Mieczysława'),
       (1, 'Romera Eugeniusza'),
       (1, 'Roosevelta Franklina Delano'),
       (1, 'Roślinna'),
       (1, 'Rosponda Stanisława'),
       (1, 'Rostafińskiego Józefa'),
       (1, 'Rowerowa'),
       (1, 'Równa'),
       (1, 'Róż Al.'),
       (1, 'Różana'),
       (1, 'Rozbrat'),
       (1, 'Roździeńskiego Walentego'),
       (1, 'Rozjazdowa'),
       (1, 'Rozjezdny Pl.'),
       (1, 'Rozmarynowa'),
       (1, 'Róży Wiatrów'),
       (1, 'Różyckiego Ludomira Al.'),
       (1, 'Rubczaka Jana'),
       (1, 'Rubinowa'),
       (1, 'Ruciana'),
       (1, 'Rudawska'),
       (1, 'Rudzka'),
       (1, 'Rumiankowa'),
       (1, 'Ruska'),
       (1, 'Rutkiewicz Wandy'),
       (1, 'Rybacka'),
       (1, 'Rybnicka'),
       (1, 'Rychła'),
       (1, 'Rychtalska'),
       (1, 'Rydygiera Ludwika'),
       (1, 'Rydza-Śmigłego Edwarda (Marszałka Edwarda Rydza-Śmigłego)'),
       (1, 'Rymarska'),
       (1, 'Rynek'),
       (1, 'Rynek Rynek'),
       (1, 'Rynek Szczepiński Pl.'),
       (1, 'Rysia'),
       (1, 'Ryska'),
       (1, 'Rytownicza'),
       (1, 'Ryżowa'),
       (1, 'Rzeczna'),
       (1, 'Rzemieślnicza'),
       (1, 'Rzepakowa'),
       (1, 'Rzeszowska'),
       (1, 'Rzeźbiarska'),
       (1, 'Rzeźnicza'),
       (1, 'Sadowa'),
       (1, 'Sądowa'),
       (1, 'Sadownicza'),
       (1, 'Salezjańska'),
       (1, 'Samborska'),
       (1, 'Samolotowa'),
       (1, 'Samotna'),
       (1, 'Samotworska'),
       (1, 'Sanocka'),
       (1, 'Saperów'),
       (1, 'Sarajewska'),
       (1, 'Sarbinowska'),
       (1, 'Sarnia'),
       (1, 'Sasankowa'),
       (1, 'Sąsiedzka'),
       (1, 'Schuberta Franza Petera'),
       (1, 'Ściegiennego Piotra (Księdza Piotra Ściegiennego)'),
       (1, 'Ścinawska'),
       (1, 'Seledynowa'),
       (1, 'Semaforowa'),
       (1, 'Sempołowskiej Stefanii'),
       (1, 'Sępa-Szarzyńskiego Mikołaja'),
       (1, 'Sępia'),
       (1, 'Serbska'),
       (1, 'Sernicka'),
       (1, 'Serowarska'),
       (1, 'Setna'),
       (1, 'Sewastopolska'),
       (1, 'Sezamkowa'),
       (1, 'Siatkarzy'),
       (1, 'Siedlecka'),
       (1, 'Siedliczan'),
       (1, 'Sielska'),
       (1, 'Siemieńskiego Lucjana'),
       (1, 'Siemiradzkiego Henryka'),
       (1, 'Sienkiewicza Henryka'),
       (1, 'Sienna'),
       (1, 'Sieradzka'),
       (1, 'Sierakowskiego Zygmunta'),
       (1, 'Sieroszowicka'),
       (1, 'Siewców'),
       (1, 'Siewierska'),
       (1, 'Siewna'),
       (1, 'Sikorcza'),
       (1, 'Sikorskiego Władysława (Generała Władysława Sikorskiego)'),
       (1, 'Siostrzana'),
       (1, 'Skałeczna'),
       (1, 'Skarbka Fryderyka'),
       (1, 'Skarbowców'),
       (1, 'Skarbu Zakrzowskiego'),
       (1, 'Skargi Piotra (Księdza Piotra Skargi)'),
       (1, 'Skarżyńskiego Stanisława (Pułkownika Stanisława Skarżyńskiego)'),
       (1, 'Skibińskiego Karola'),
       (1, 'Skibowa'),
       (1, 'Skierniewicka'),
       (1, 'Składowa'),
       (1, 'Skoczna'),
       (1, 'Skoczylasa Władysława'),
       (1, 'Skopijska'),
       (1, 'Skoroszowska'),
       (1, 'Skrajna'),
       (1, 'Skrzetuskiego Jana'),
       (1, 'Skrzydlata'),
       (1, 'Skwerowa'),
       (1, 'Skwierzyńska'),
       (1, 'Skwierzyńska'),
       (1, 'Śląska Al.'),
       (1, 'Sławka Walerego'),
       (1, 'Ślązaka Anioła'),
       (1, 'Ślazowa'),
       (1, 'Ślebodzińskiego Władysława'),
       (1, 'Ślepa'),
       (1, 'Ślewińskiego Władysława'),
       (1, 'Ślężańska'),
       (1, 'Ślężna'),
       (1, 'Ślęzoujście'),
       (1, 'Śliczna'),
       (1, 'Śliwkowa'),
       (1, 'Śliwowa Al.'),
       (1, 'Słodowa Wyspa'),
       (1, 'Słodowe Przejście'),
       (1, 'Słomiana'),
       (1, 'Słoneczna'),
       (1, 'Słonecznikowa'),
       (1, 'Słoneczny Bulw.'),
       (1, 'Słonimska'),
       (1, 'Słonimskiego Antoniego'),
       (1, 'Słotna'),
       (1, 'Słowacka'),
       (1, 'Słowackiego Juliusza Wybrz.'),
       (1, 'Słowiańska'),
       (1, 'Słowiański Pl.'),
       (1, 'Słowicza'),
       (1, 'Słowińców'),
       (1, 'Słubicka'),
       (1, 'Słupska'),
       (1, 'Ślusarska'),
       (1, 'Smardzowska'),
       (1, 'Smętna'),
       (1, 'Śmigła'),
       (1, 'Smocza'),
       (1, 'Smolecka'),
       (1, 'Smoleńskiego Jerzego Józefa'),
       (1, 'Smolna'),
       (1, 'Smoluchowskiego Mariana'),
       (1, 'Śniadeckich Jana I Jędrzeja'),
       (1, 'Śniegockiego Michała'),
       (1, 'Śnieżna'),
       (1, 'Snopkowa'),
       (1, 'Snycerska'),
       (1, 'Sobieskiego Jana Iii Al.'),
       (1, 'Sobieszowska'),
       (1, 'Sobocińska'),
       (1, 'Sobótki'),
       (1, 'Sochaczewska'),
       (1, 'Sojowa'),
       (1, 'Sokalska'),
       (1, 'Sokola'),
       (1, 'Sokolnicza'),
       (1, 'Solidarności Pl.'),
       (1, 'Solidarności Walczącej Skw.'),
       (1, 'Solińska'),
       (1, 'Solny Pl.'),
       (1, 'Solskiego Ludwika'),
       (1, 'Sołtysia'),
       (1, 'Sołtysowicka'),
       (1, 'Sopocka'),
       (1, 'Sorkwicka'),
       (1, 'Sosnkowskiego Kazimierza (Generała Kazimierza Sosnkowskiego)'),
       (1, 'Sosnowa'),
       (1, 'Sosnowiecka'),
       (1, 'Sowia'),
       (1, 'Sowińskiego Józefa (Generała Józefa Sowińskiego)'),
       (1, 'Spacerowa'),
       (1, 'Spadochroniarzy'),
       (1, 'Spawaczy'),
       (1, 'Spiska'),
       (1, 'Spiżowa'),
       (1, 'Spokojna'),
       (1, 'Spółdzielcza'),
       (1, 'Społeczna'),
       (1, 'Sportowa'),
       (1, 'Srebrnogórska'),
       (1, 'Srebrny Pl.'),
       (1, 'Średzka'),
       (1, 'Srocza'),
       (1, 'Środkowa'),
       (1, 'Śrubowa'),
       (1, 'Śrutowa'),
       (1, 'Stabłowicka'),
       (1, 'Stachury Edwarda'),
       (1, 'Stacyjna'),
       (1, 'Staffa Leopolda'),
       (1, 'Stajenna'),
       (1, 'Stalowa'),
       (1, 'Stalowowolska'),
       (1, 'Stanisławowska'),
       (1, 'Stanisławskiego Jana'),
       (1, 'Stanki Jana'),
       (1, 'Stanów Zjednoczonych'),
       (1, 'Stargardzka'),
       (1, 'Starobielawska'),
       (1, 'Starodębowa'),
       (1, 'Starodworska'),
       (1, 'Starogajowa'),
       (1, 'Starograniczna'),
       (1, 'Staroleska'),
       (1, 'Staromłyńska'),
       (1, 'Staropolska'),
       (1, 'Starościńska'),
       (1, 'Starzyńskiego Stefana'),
       (1, 'Staszica Stanisława Pl.'),
       (1, 'Stawowa'),
       (1, 'Stefczyka Franciszka'),
       (1, 'Stefki Kamila'),
       (1, 'Stein Edyty (Błogosławionego Edyty Stein)'),
       (1, 'Steinhausa Hugona'),
       (1, 'Sterowcowa'),
       (1, 'Stobrawska'),
       (1, 'Stoczniowa'),
       (1, 'Stodolna'),
       (1, 'Stokrotkowa'),
       (1, 'Stolarska'),
       (1, 'Stopnicka'),
       (1, 'Storczykowa'),
       (1, 'Strachocińska'),
       (1, 'Strachowicka'),
       (1, 'Strachowskiego Bartłomieja'),
       (1, 'Strączkowa'),
       (1, 'Stradomska'),
       (1, 'Straussa Johanna'),
       (1, 'Strażacka'),
       (1, 'Strażnicza'),
       (1, 'Stroma'),
       (1, 'Strońska'),
       (1, 'Struga Andrzeja'),
       (1, 'Strumykowa'),
       (1, 'Stryjska'),
       (1, 'Strzeblowska'),
       (1, 'Strzegomska'),
       (1, 'Strzegomska'),
       (1, 'Strzegomski Pl.'),
       (1, 'Strzelecka'),
       (1, 'Strzelecki Pl.'),
       (1, 'Studzienna'),
       (1, 'Stwosza Wita'),
       (1, 'Stysia Wincentego'),
       (1, 'Sucha'),
       (1, 'Suchardy Edwarda'),
       (1, 'Sucharskiego Henryka (Majora Henryka Sucharskiego)'),
       (1, 'Sudecka'),
       (1, 'Sukielicka'),
       (1, 'Sukiennice'),
       (1, 'Sulejowska'),
       (1, 'Sulistrowska'),
       (1, 'Sulmierzycka'),
       (1, 'Sułowska'),
       (1, 'Supińskiego Józefa'),
       (1, 'Suskiego Mariana'),
       (1, 'Suwalska'),
       (1, 'Świątnicka'),
       (1, 'Świdnicka'),
       (1, 'Świdrowa'),
       (1, 'Świebodzka'),
       (1, 'Świeradowska'),
       (1, 'Świerkowa'),
       (1, 'Świętego Antoniego'),
       (1, 'Świętego Ducha'),
       (1, 'Świętego Huberta'),
       (1, 'Świętego Idziego'),
       (1, 'Świętego Jerzego'),
       (1, 'Świętego Józefa'),
       (1, 'Świętego Krzysztofa Pl.'),
       (1, 'Świętego Macieja Pl.'),
       (1, 'Świętego Marcina'),
       (1, 'Świętego Mikołaja'),
       (1, 'Świętego Pawła'),
       (1, 'Świętego Wincentego'),
       (1, 'Świętego Wita'),
       (1, 'Świętej Anny'),
       (1, 'Świętej Barbary'),
       (1, 'Świętej Doroty'),
       (1, 'Świętej Elżbiety'),
       (1, 'Świętej Jadwigi'),
       (1, 'Świętej Katarzyny'),
       (1, 'Świętej Marii Magdaleny'),
       (1, 'Świętej Trójcy'),
       (1, 'Świętochłowicka'),
       (1, 'Świętochowskiego Aleksandra'),
       (1, 'Świętojański Pl.'),
       (1, 'Świętokrzyska'),
       (1, 'Świeża'),
       (1, 'Świnoujska'),
       (1, 'Świstackiego Stacha'),
       (1, 'Świt'),
       (1, 'Swobodna'),
       (1, 'Swojczycka'),
       (1, 'Sycowska'),
       (1, 'Sygnałowa'),
       (1, 'Syjamska'),
       (1, 'Synów Pułku'),
       (1, 'Syrokomli Władysława'),
       (1, 'Szachistów'),
       (1, 'Szafera Władysława'),
       (1, 'Szafirowa'),
       (1, 'Szafranowa'),
       (1, 'Szajnochy Karola'),
       (1, 'Szałwiowa'),
       (1, 'Szanieckiego Jana'),
       (1, 'Szara'),
       (1, 'Szarotkowa'),
       (1, 'Szarskiego Kazimierza Witalisa'),
       (1, 'Szarugi'),
       (1, 'Szarych Szeregów'),
       (1, 'Szczawiowa'),
       (1, 'Szczecińska'),
       (1, 'Szczepanowska'),
       (1, 'Szczepińska'),
       (1, 'Szczepowa'),
       (1, 'Szczęśliwa'),
       (1, 'Szczycieńska'),
       (1, 'Szczygla'),
       (1, 'Szczyrki Jana'),
       (1, 'Szczytnicka'),
       (1, 'Szeli Jakuba Pl.'),
       (1, 'Szewczenki Tarasa'),
       (1, 'Szewska'),
       (1, 'Szkarłatna'),
       (1, 'Szklarska'),
       (1, 'Szkocka'),
       (1, 'Szkolna'),
       (1, 'Szkutnicza'),
       (1, 'Szlifierska'),
       (1, 'Szmaragdowa'),
       (1, 'Szniolisa Aleksandra'),
       (1, 'Szolc-Rogozińskiego Stefana'),
       (1, 'Szpacza'),
       (1, 'Szparagowa'),
       (1, 'Szpilkowa'),
       (1, 'Szpitalna'),
       (1, 'Szprotawska'),
       (1, 'Szramka Emila (Księdza Emila Szramka)'),
       (1, 'Szronowa'),
       (1, 'Sztabowa'),
       (1, 'Sztabowa'),
       (1, 'Szwajcarska'),
       (1, 'Szwedzka'),
       (1, 'Szwoleżerska'),
       (1, 'Szybka'),
       (1, 'Szybowcowa'),
       (1, 'Szymanowskiego Karola'),
       (1, 'Tallińska'),
       (1, 'Tamka Wyspa'),
       (1, 'Tańskiego Czesława'),
       (1, 'Tapicerska'),
       (1, 'Tarninowa'),
       (1, 'Tarnobrzeska'),
       (1, 'Tarnogajska'),
       (1, 'Tarnogórska'),
       (1, 'Tarnopolska'),
       (1, 'Tarnowska'),
       (1, 'Taszyckiego Witolda'),
       (1, 'Tatarakowa'),
       (1, 'Tatarska'),
       (1, 'Tatrzańska'),
       (1, 'Tczewska'),
       (1, 'Teatralna'),
       (1, 'Teatralny Pl.'),
       (1, 'Tęczowa'),
       (1, 'Tenisowa'),
       (1, 'Terenowa'),
       (1, 'Tkacka'),
       (1, 'Tokarska'),
       (1, 'Tolkmicka'),
       (1, 'Tomaszowska'),
       (1, 'Topolowa'),
       (1, 'Torfowa'),
       (1, 'Torowa'),
       (1, 'Toruńska'),
       (1, 'Towarowa'),
       (1, 'Trakcyjna'),
       (1, 'Traktatowa'),
       (1, 'Traktorowa'),
       (1, 'Tramwajowa'),
       (1, 'Traugutta Romualda (Generała Romualda Traugutta)'),
       (1, 'Trawna'),
       (1, 'Trawowa'),
       (1, 'Trentowskiego Bronisława'),
       (1, 'Treski Jerzego'),
       (1, 'Trójkątna'),
       (1, 'Truskawkowa'),
       (1, 'Trwała'),
       (1, 'Trzebiatowskiego Włodzimierza'),
       (1, 'Trzebnicka'),
       (1, 'Trzebnicka'),
       (1, 'Trzebowiańska'),
       (1, 'Trzemeska'),
       (1, 'Trzmielowicka'),
       (1, 'Tulipanowa'),
       (1, 'Tunelowa'),
       (1, 'Turecka'),
       (1, 'Turkusowa'),
       (1, 'Turniejowa'),
       (1, 'Turoszowska'),
       (1, 'Turystyczna'),
       (1, 'Tuwima Juliana'),
       (1, 'Twarda'),
       (1, 'Twardogórska'),
       (1, 'Tybetańska'),
       (1, 'Tylna'),
       (1, 'Tymiankowa'),
       (1, 'Tyniecka'),
       (1, 'Tyrmanda Leopolda'),
       (1, 'Tyska'),
       (1, 'Ubocze'),
       (1, 'Uciechowska'),
       (1, 'Uczniowska'),
       (1, 'Udzieli Seweryna'),
       (1, 'Ujejskiego Kornela'),
       (1, 'Ukraińska'),
       (1, 'Ukryta'),
       (1, 'Ulanowskiego Bolesława'),
       (1, 'Ułańska'),
       (1, 'Ulowa'),
       (1, 'Uniwersytecka'),
       (1, 'Uniwersytecki Pl.'),
       (1, 'Unruga Józefa (Admirała Józefa Unruga)'),
       (1, 'Upalna'),
       (1, 'Urbańskiego Jana Jerzego'),
       (1, 'Ustronie'),
       (1, 'Uznamska'),
       (1, 'Uznańskiego Adama'),
       (1, 'Vinci Leonarda Da'),
       (1, 'Vivaldiego Antonio'),
       (1, 'Wadowicka'),
       (1, 'Waflowa'),
       (1, 'Wagnera Ryszarda'),
       (1, 'Wagonowa'),
       (1, 'Wałbrzyska'),
       (1, 'Walecznych'),
       (1, 'Waligórskiego Andrzeja'),
       (1, 'Wallenroda Konrada'),
       (1, 'Walońska'),
       (1, 'Wałowa'),
       (1, 'Wambierzycka'),
       (1, 'Wandy'),
       (1, 'Waniliowa'),
       (1, 'Wańkowicza Melchiora'),
       (1, 'Wapienna'),
       (1, 'Warciańska'),
       (1, 'Wardzyńskich Władysława I Jana'),
       (1, 'Warmińska'),
       (1, 'Warszawska'),
       (1, 'Warsztatowa'),
       (1, 'Wartka'),
       (1, 'Waryńskiego Ludwika'),
       (1, 'Warzywnicza'),
       (1, 'Wąska'),
       (1, 'Wąsowicza Józefa'),
       (1, 'Watowa'),
       (1, 'Wawrzyniaka Piotra (Księdza Piotra Wawrzyniaka)'),
       (1, 'Wędkarzy'),
       (1, 'Wędrowców'),
       (1, 'Węgierska'),
       (1, 'Węgoborska'),
       (1, 'Weigla Rudolfa'),
       (1, 'Wejherowska'),
       (1, 'Wełniana'),
       (1, 'Wereszyckiego Henryka'),
       (1, 'Wesoła'),
       (1, 'Wesołowskiego Jana'),
       (1, 'Westerplatte Pl.'),
       (1, 'Wiaduktowa'),
       (1, 'Wiązowa Al.'),
       (1, 'Widawska'),
       (1, 'Widłakowa'),
       (1, 'Widna'),
       (1, 'Widok'),
       (1, 'Więckowskiego Stanisława'),
       (1, 'Wieczorna'),
       (1, 'Wieczysta'),
       (1, 'Wiedeńska'),
       (1, 'Wiejska'),
       (1, 'Wieletów'),
       (1, 'Wielka'),
       (1, 'Wielkiego Kazimierza'),
       (1, 'Wielkopolska'),
       (1, 'Wieluńska'),
       (1, 'Wieniawskiego Henryka'),
       (1, 'Wieruszowska'),
       (1, 'Wierzbowa'),
       (1, 'Wierzchowicka'),
       (1, 'Wierzyńskiego Kazimierza'),
       (1, 'Wieśniacza'),
       (1, 'Wietnamska'),
       (1, 'Wietrzna'),
       (1, 'Więzienna'),
       (1, 'Wilanowska'),
       (1, 'Wilcza'),
       (1, 'Wilczkowska'),
       (1, 'Wilczycka'),
       (1, 'Wileńska'),
       (1, 'Wilgotna'),
       (1, 'Wilgowa'),
       (1, 'Wilkszyńska'),
       (1, 'Wińska'),
       (1, 'Wiosenna'),
       (1, 'Wiślańska'),
       (1, 'Wiślany Pl.'),
       (1, 'Wiśniowa Al.'),
       (1, 'Witebska'),
       (1, 'Witelona'),
       (1, 'Witkowska'),
       (1, 'Witosa Wincentego'),
       (1, 'Wittek Marii (Generał Marii Wittek)'),
       (1, 'Wittiga Edwarda'),
       (1, 'Wiwulskiego Antoniego'),
       (1, 'Włada Franciszka (Generała Franciszka Włada)'),
       (1, 'Władysława Jagiełły'),
       (1, 'Władysława Łokietka'),
       (1, 'Włodkowica Pawła'),
       (1, 'Włościańska'),
       (1, 'Wodna'),
       (1, 'Wodzisławska'),
       (1, 'Wojaczka Rafała'),
       (1, 'Wojanowska'),
       (1, 'Wojciecha Z Brudzewa'),
       (1, 'Wojnowska'),
       (1, 'Wojrowicka'),
       (1, 'Wojska Polskiego'),
       (1, 'Wojszycka'),
       (1, 'Wojtkiewicza Witolda'),
       (1, 'Wolbromska'),
       (1, 'Wołczyńska'),
       (1, 'Wolfkego Mieczysława'),
       (1, 'Wołgogradzka'),
       (1, 'Wolinian'),
       (1, 'Wolności Pl.'),
       (1, 'Wołodyjowskiego Michała'),
       (1, 'Wołodyjowskiej Basi'),
       (1, 'Wołowska'),
       (1, 'Wolska'),
       (1, 'Wołyńska'),
       (1, 'Worcella Stanisława'),
       (1, 'Woronowicka'),
       (1, 'Woskowa'),
       (1, 'Woźnicza'),
       (1, 'Wróbla'),
       (1, 'Wróblewskiego Walerego Pl. (Generała Walerego Wróblewskiego)'),
       (1, 'Wróblewskiego Zygmunta'),
       (1, 'Wrocławczyka Michała'),
       (1, 'Wronia'),
       (1, 'Wschodnia'),
       (1, 'Wschowska'),
       (1, 'Wspólna'),
       (1, 'Wszystkich Świętych'),
       (1, 'Wybickiego Józefa (Generała Józefa Wybickiego)'),
       (1, 'Wyboista'),
       (1, 'Wyczółkowskiego Leona'),
       (1, 'Wygodna'),
       (1, 'Wykładowa'),
       (1, 'Wylotowa'),
       (1, 'Wynalazców'),
       (1, 'Wyścigowa'),
       (1, 'Wysłoucha Seweryna'),
       (1, 'Wysockiego Piotra'),
       (1, 'Wysoka'),
       (1, 'Wyspiańskiego Stanisława Wybrz.'),
       (1, 'Wystawowa'),
       (1, 'Wyszyńskiego Stefana (Stefana Kardynała Wyszyńskiego)'),
       (1, 'Wyszyńskiego Stefana Bulw. (Stefana Kardynała Wyszyńskiego)'),
       (1, 'Wyzwolenia Pl.'),
       (1, 'Żabia Ścieżka'),
       (1, 'Ząbkowicka'),
       (1, 'Zabłocie'),
       (1, 'Zabrodzka'),
       (1, 'Zabrzańska'),
       (1, 'Zachodnia'),
       (1, 'Zagaje'),
       (1, 'Zagajnikowa'),
       (1, 'Żagańska'),
       (1, 'Zagłębiowska'),
       (1, 'Zagłoby Onufrego'),
       (1, 'Zagony'),
       (1, 'Zagrodnicza'),
       (1, 'Zagrzebska'),
       (1, 'Zajączkowska'),
       (1, 'Zajazdowa'),
       (1, 'Zajęcza'),
       (1, 'Zaka Eugeniusza'),
       (1, 'Zakładowa'),
       (1, 'Zakopiańska'),
       (1, 'Zakrzowska'),
       (1, 'Zaleskiego Bohdana'),
       (1, 'Zalewowa'),
       (1, 'Załęże'),
       (1, 'Zalipie'),
       (1, 'Zamenhofa Ludwika Pl.'),
       (1, 'Zamkowa'),
       (1, 'Zamojska'),
       (1, 'Zamoyskiego Jana'),
       (1, 'Zaolziańska'),
       (1, 'Zapaśnicza'),
       (1, 'Zapolskiej Gabrieli'),
       (1, 'Zaporoska'),
       (1, 'Zaporoska'),
       (1, 'Zaporoska'),
       (1, 'Zapotocze'),
       (1, 'Zarembowicza Władysława'),
       (1, 'Żarska'),
       (1, 'Zarzecze'),
       (1, 'Zaściankowa'),
       (1, 'Zastępowa'),
       (1, 'Zatorska'),
       (1, 'Zaułek Rogoziński'),
       (1, 'Zaułek Wolski'),
       (1, 'Zawalna'),
       (1, 'Zawierciańska'),
       (1, 'Zawońska'),
       (1, 'Zaziębie'),
       (1, 'Zbarska'),
       (1, 'Zbożowa'),
       (1, 'Zdrojowa'),
       (1, 'Zdrowa'),
       (1, 'Zduńska'),
       (1, 'Zebrzydowska'),
       (1, 'Zefirowa'),
       (1, 'Zegadłowicza Emila'),
       (1, 'Zegarmistrzowska'),
       (1, 'Żegiestowska'),
       (1, 'Żeglarska'),
       (1, 'Żelazna'),
       (1, 'Żelaźnicze Przejście'),
       (1, 'Zelenaya Tadeusza'),
       (1, 'Zelwerowicza Aleksandra'),
       (1, 'Zemska'),
       (1, 'Żeńców'),
       (1, 'Żernicka'),
       (1, 'Żeromskiego Stefana'),
       (1, 'Zgodna'),
       (1, 'Zgody Pl.'),
       (1, 'Zgorzelecka'),
       (1, 'Ziębicka'),
       (1, 'Zielińskiego Tadeusza'),
       (1, 'Zielna'),
       (1, 'Zielona'),
       (1, 'Zielonego Dębu'),
       (1, 'Zielonogórska'),
       (1, 'Ziemniaczana'),
       (1, 'Ziemowita'),
       (1, 'Zimowa'),
       (1, 'Żiżki Jana'),
       (1, 'Złocieniowa'),
       (1, 'Złota'),
       (1, 'Złotej Lilii'),
       (1, 'Złotnicka'),
       (1, 'Złotoryjska'),
       (1, 'Złotostocka'),
       (1, 'Złotowska'),
       (1, 'Żmichowskiej Narcyzy'),
       (1, 'Żmigrodzka'),
       (1, 'Zmorskiego Romana'),
       (1, 'Żmudzka'),
       (1, 'Żniwna'),
       (1, 'Zoli Emila'),
       (1, 'Żółkiewskiego Stanisława'),
       (1, 'Żołnierska'),
       (1, 'Żółta'),
       (1, 'Źródlana'),
       (1, 'Żubrza'),
       (1, 'Zuchowa'),
       (1, 'Żurawia'),
       (1, 'Żużlowców'),
       (1, 'Żwawa'),
       (1, 'Zwiadowców'),
       (1, 'Żwirki I Wigury'),
       (1, 'Żwirowa'),
       (1, 'Zwrotnicza'),
       (1, 'Zwycięska'),
       (1, 'Zyndrama Z Maszkowic'),
       (1, 'Żytnia'),
       (1, 'Żytomierska'),
       (1, 'Żywiecka'),
       (1, 'Żywopłotowa');